### ISSUE TITLE
Broken link in production

### ISSUE THREAD

**Issue by nabchar** [iseessel/Poll-Paradise#1]
Hey Isaac,

Noticed that you have a broken link to this github repo currently in production.
<img width="1440" alt="screen shot 2017-12-19 at 3 29 49 pm" src="https://user-images.githubusercontent.com/17883890/34177454-9aca99e8-e4d1-11e7-938d-1fb15801d27e.png">

Just thought I'd note it here for you. 

Goodluck!

**Comment by iseessel** [comment]
Thank you!
